[package]
name = "add-it"
version = "0.1.0"
authors = ["Taimoorkhan1122 <46717905+Taimoorkhan1122@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
serde = "1.0.117"
